CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER PRIMARY KEY,             
    EMPLOYEE_NAME VARCHAR2(50),         
    SALARY NUMBER                        
);
INSERT INTO EMPLOYEES VALUES (1, 'Alice', 2500);
INSERT INTO EMPLOYEES VALUES (2, 'Bob', 3200);
INSERT INTO EMPLOYEES VALUES (3, 'Charlie', 2800);
INSERT INTO EMPLOYEES VALUES (4, 'Diana', 4000);
INSERT INTO EMPLOYEES VALUES (5, 'Eve', 1500);
INSERT INTO EMPLOYEES VALUES (6, 'Frank', 3000);
INSERT INTO EMPLOYEES VALUES (7, 'Grace', 2200);
INSERT INTO EMPLOYEES VALUES (8, 'Helen', 3800);
INSERT INTO EMPLOYEES VALUES (9, 'Ivan', 2600);
INSERT INTO EMPLOYEES VALUES (10, 'Jenny', 3300);

select * from EMPLOYEES ;